version: "3.7"
services:
  minio: 
    image: minio/minio:latest
    pull_policy: always
    dns: 0.0.0.0 
    ports:
      - "16000:9000"
      - "16001:9001"
    environment:
      # MINIO_ACCESS_KEY: minioKey
      # MINIO_SECRET_KEY: minioSecret
      MINIO_ROOT_USER: minioKey
      MINIO_ROOT_PASSWORD: minioSecret
      MINIO_BUCKET: techainer
    command: server /data --console-address ":9001"
    depends_on:
      - layout_model_storage

  layout_model_storage:
    restart: always
    pull_policy: always
    image: techainer1t/lib_layout_db:model_storage-triton_flow-10d69a6c
    environment: 
      AWS_ACCESS_KEY_ID: minioKey
      AWS_SECRET_ACCESS_KEY: minioSecret
      AWS_BUCKET: techainer
      AWS_S3_ENDPOINT_URL: http://minio:9000

  triton:
    restart: always
    pull_policy: never
    image: techainer1t/base_docker:tritonserver_full_2208-93dada6e
    ports:
      - "8000"
      - "8001"
      - "8002"
    command: tritonserver --model-repository=s3://http://minio:9000/techainer/models --strict-model-config=false --exit-on-error=false --model-control-mode=poll --repository-poll-secs=5
    environment: 
      AWS_ACCESS_KEY_ID: minioKey
      AWS_SECRET_ACCESS_KEY: minioSecret
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu, utility, compute, video]
    depends_on:
      - minio

  layout_triton:
    restart: always
    # pull_policy: always
    image: techainer1t/lib_layout_db:triton-triton_flow-10d69a6c
    dns: 0.0.0.0 
    ports:
      - "32701:8095"
    environment:
      GUNICORN_WORKERS: 1
      GUNICORN_THREADS: 16
      triton_url: "triton:8000"
    command: mlchain serve mlchain run -c mlconfig.yaml -m triton
    depends_on:
      - triton